name: nepali_lyricapp_upgraded
description: A Upgraded lyric app project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.1
  url_launcher: ^6.1.2
  rename: ^2.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

  # flutter splash packge start 
  flutter_native_splash: ^2.1.6
flutter_native_splash:

  android: true
  web: true
  ios: false

  #color: "#FFCC00"  #Yello
  color: "#ffffff"  #white
  #background_Image: "asset/splashbackground"
  image: assets/splash800.png

  android_gravity : center
  ios_gravity : center
  web_image_mode: center

  #fullscreen: true
  android12: true
  # flutter splash packge End

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Dosis
      fonts:
        - asset: fonts/Dosis-Regular.ttf
        - asset: fonts/Dosis-Medium.ttf
          weight: 400
    - family: Oswald
      fonts:
        - asset: fonts/Oswald-Regular.ttf
        - asset: fonts/Oswald-Medium.ttf
          weight: 400
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
